### ISSUE TITLE
Fix unicode handling against API.

### ISSUE THREAD

**Issue by migurski** [codeforamerica/brigade-alpha#52]
Map links do not set correct URLs for organization names with unicode content.

Steps to reproduce:

1. Visit http://www.codeforamerica.org/brigade/index/Code-for-Warsaw
2. Pan to the west and slightly south, to the city of Łódź, click the marker.
3. The URL incorrectly changes to http://www.codeforamerica.org/brigade/index/Code-for-%25C5%2581%25C3%25B3d%25C5%25BA instead of http://www.codeforamerica.org/brigade/index/Code-for-%25C5%2581%25C3%25B3d%25C5%25BA

Related behavior:

1. Visit http://www.codeforamerica.org/brigade/index/Code-for-Łódź
2. Note that brigade info panel is correct, but map does not navigate to Poland.

Note that these both work:
* http://www.codeforamerica.org/api/organizations/Code-for-Łódź
* http://www.codeforamerica.org/api/organizations/Code-for-%C5%81%C3%B3d%C5%BA

Also, http://www.codeforamerica.org/brigade/index/Code-for-%C5%81%C3%B3d%C5%BA should be a synonym for http://www.codeforamerica.org/brigade/index/Code-for-Łódź

Tested in Safari 7, Chrome 32, and Firefox 27.

**Comment by ondrae** [comment]
Fixed in the CfAPI a while ago.
