### ISSUE TITLE
Add padding to organize page header

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade-alpha#77]
the mobile menu overlaps the heading on mobile. 
![image](https://cloud.githubusercontent.com/assets/595778/5055307/507360d2-6c16-11e4-865c-429cfd9100a6.jpg)

**Comment by esolar07** [comment]
Is this still an issue?

**Comment by ondrae** [comment]
@esolar07 It is. Should be as simple as adding a `margin-top: 50px;` to `main` in the css.

**Comment by esolar07** [comment]
@ondrae commit a change.
